sudo: required

services:
  - docker

before_install:
  - docker build -t shalama/docker_react -f Dockerfile.dev .

script:
  - docker run shalama/docker_react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucker_name: "elasticbeanstalk-eu-central-1-265338444229"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id : $access_key_id
  secret_access_key: $secret_access_key
